# Ranking via Python

# Creating Team List

In [1]:
n = int(input("Enter Number of Teams: "))
teams = []
for i in range(n):
    print(str(i+1)+ ". ", end = " ")
    team = input("Team: ")
    teams.append(team)
print("\n", teams)

Enter Number of Teams: 5
1.  Team: SL
2.  Team: SA
3.  Team: NZ
4.  Team: E
5.  Team: NE

 ['SL', 'SA', 'NZ', 'E', 'NE']


# Creating Matrix

In [ ]:
import numpy as np
l = []

print("Enter '1' if first team wins, else '0'.")
for i in range(len(teams)):
    l.append([])
    for j in range(len(teams)):
        if i==j:
            l[i].append(0)
        else:
            if j>i:
                print(teams[i], " Vs ", teams[j], " :", end = " ")
                wol = int(input())
                l[i].append(wol)
            else:
                if l[j][i]== 1:
                    l[i].append(0)
                else:
                    l[i].append(1)
                    
mat = np.matrix(l)
print("\n", mat)

Enter '1' if first team wins, else '0'.
SL  Vs  SA  : 1
SL  Vs  NZ  : 1
SL  Vs  E  : 0
SL  Vs  NE  : 1
SA  Vs  NZ  : 1
SA  Vs  E  : 1
SA  Vs  NE  : 1
NZ  Vs  E  : 1
NZ  Vs  NE  : 1
E  Vs  NE  : 

# Finding Dominant Eigen Value and Eigen Vector via Power Method1  

In [ ]:
"""import numpy as np
row = int(input("Enter number of Rows: "))
col = int(input("Enter number of Columns: "))
def create_matrix():
    mat = []
    
    for x in range(row):
        mat.append([])
        for y in range(col):
            a = int(input("Enter Number: "))
            mat[x].append(a)

    mat = np.matrix(mat)
    print(mat)
    return mat
mat = create_matrix()"""

In [6]:
unit = np.ones((n,1))
m = np.matrix(unit)

b = True
itr = 0
while b:
    itr += 1
    y = 0
    p = mat@m
    x = p.max()
    p = p / x

    for i in range(n):
        if round(p.item(i), 4) == round(m.item(i), 4):
            y += 1

    print("\n\n Iteration Number: ", itr, "\n")

    if(y == n):
         b=False
        
    print("Eigen Value: ",x)
    print("Eigen Vector: \n",p)        
    
    m = p



 Iteration Number:  1 

Eigen Value:  6.0
Eigen Vector: 
 [[0.66666667]
 [0.33333333]
 [0.5       ]
 [1.        ]
 [1.        ]
 [0.5       ]
 [0.16666667]
 [0.5       ]]


 Iteration Number:  2 

Eigen Value:  3.1666666666666665
Eigen Vector: 
 [[0.47368421]
 [0.21052632]
 [0.63157895]
 [1.        ]
 [0.84210526]
 [0.31578947]
 [0.15789474]
 [0.36842105]]


 Iteration Number:  3 

Eigen Value:  2.368421052631579
Eigen Vector: 
 [[0.44444444]
 [0.22222222]
 [0.71111111]
 [1.        ]
 [0.91111111]
 [0.42222222]
 [0.26666667]
 [0.46666667]]


 Iteration Number:  4 

Eigen Value:  2.7333333333333334
Eigen Vector: 
 [[0.50406504]
 [0.26829268]
 [0.6097561 ]
 [1.        ]
 [0.92682927]
 [0.43902439]
 [0.2601626 ]
 [0.51219512]]


 Iteration Number:  5 

Eigen Value:  2.9105691056910565
Eigen Vector: 
 [[0.50837989]
 [0.26536313]
 [0.60893855]
 [1.        ]
 [0.89106145]
 [0.39106145]
 [0.20949721]
 [0.44972067]]


 Iteration Number:  6 

Eigen Value:  2.7150837988826817
Eigen Vector: 
 [

# Ranking

In [8]:
rank = []
rankus = []
for i in range(n):
    rank.append(p.item(i))
    rankus.append(p.item(i))
rank.sort()
print(rank)
print(rankus)

for i in range(n):
    print("\n\n", teams[rankus.index(rank[-(i+1)])])

del rank
del rankus

[0.2309897261698752, 0.2525126786629896, 0.4069039347918018, 0.46306769094480976, 0.49243332859688127, 0.6348892215544106, 0.9025946757240018, 1.0]
[0.49243332859688127, 0.2525126786629896, 0.6348892215544106, 1.0, 0.9025946757240018, 0.4069039347918018, 0.2309897261698752, 0.46306769094480976]


 Mumbai Indians


 Kolkata Knight Riders


 Rising Pune Supergiants


 Sunrisers Hyderabad


 Delhi Daredevils


 Kings XI Punjab


 Royal Challengers Bangalore


 Gujrat Lions
