# Ranking via Python

# Creating Team List

In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv('C:\\Users\\HP\\Desktop\\ipl2017 maths assignment.csv', )
teamsl = list(data)
teams = []
for x in range(1,9):
    teams.append(teamsl[x])
print("\n", teams)


 ['Sunrisers Hyderabad', 'Royal Challengers Bangalore', 'Rising Pune Supergiants', 'Mumbai Indians', 'Kolkata Knight Riders', 'Kings XI Punjab', 'Gujarat Lions', 'Delhi Daredevils']


# Creating Matrix

In [8]:
mat = pd.read_csv('C:\\Users\\HP\\Desktop\\ipl2017 maths assignment.csv')
print(mat, "\n\n\n")

n = 8

mat = np.matrix(mat)
mat2 = []
for x in range(8):
    mat2.append([])
    for y in range(1, 9):
        mat2[x].append(mat[x , y])
        
mat = np.matrix(mat2)
print(mat)

                    Unnamed: 0  Sunrisers Hyderabad  \
0          Sunrisers Hyderabad                    0   
1  Royal Challengers Bangalore                    0   
2      Rising Pune Supergiants                    2   
3               Mumbai Indians                    1   
4        Kolkata Knight Riders                    1   
5              Kings XI Punjab                    0   
6                Gujarat Lions                    0   
7             Delhi Daredevils                    1   

   Royal Challengers Bangalore  Rising Pune Supergiants  Mumbai Indians  \
0                            1                        0               1   
1                            0                        0               0   
2                            2                        0               1   
3                            2                        0               0   
4                            2                        1               0   
5                            2                        

# Finding Dominant Eigen Value and Eigen Vector via Power Method  

In [3]:
import numpy as np
unit = np.ones((n,1))
m = np.matrix(unit)

b = True
itr = 0
while b:
    itr += 1
    y = 0
    p = mat@m
    x = p.max()
    p = p / x

    for i in range(n):
        if round(p.item(i), 4) == round(m.item(i), 4):
            y += 1

    print("\n\n Iteration Number: ", itr, "\n")

    if(y == n):
         b=False
        
    print("Eigen Value: ",x)
    print("Eigen Vector: \n",p)        
    
    m = p



 Iteration Number:  1 

Eigen Value:  10.0
Eigen Vector: 
 [[0.8]
 [0.3]
 [0.8]
 [1. ]
 [0.8]
 [0.7]
 [0.4]
 [0.6]]


 Iteration Number:  2 

Eigen Value:  5.7
Eigen Vector: 
 [[0.85964912]
 [0.28070175]
 [0.89473684]
 [1.        ]
 [0.78947368]
 [0.73684211]
 [0.45614035]
 [0.68421053]]


 Iteration Number:  3 

Eigen Value:  6.017543859649123
Eigen Vector: 
 [[0.85422741]
 [0.303207  ]
 [0.87463557]
 [1.        ]
 [0.81049563]
 [0.72886297]
 [0.44897959]
 [0.71428571]]


 Iteration Number:  4 

Eigen Value:  6.137026239067055
Eigen Vector: 
 [[0.84465558]
 [0.30593824]
 [0.86413302]
 [1.        ]
 [0.80522565]
 [0.72589074]
 [0.44275534]
 [0.68931116]]


 Iteration Number:  5 

Eigen Value:  6.0570071258907365
Eigen Vector: 
 [[0.84823529]
 [0.30070588]
 [0.87090196]
 [1.        ]
 [0.80368627]
 [0.72862745]
 [0.44596078]
 [0.69082353]]


 Iteration Number:  6 

Eigen Value:  6.059215686274509
Eigen Vector: 
 [[0.84901948]
 [0.30162449]
 [0.87076565]
 [1.        ]
 [0.80485405]
 [0

# Ranking

In [6]:
rank = []
rankus = []
for i in range(n):
    rank.append(p.item(i))
    rankus.append(p.item(i))
rank.sort()

for i in range(n):
    print(teams[rankus.index(rank[-(i+1)])], "\n")

del rank
del rankus

Mumbai Indians 

Rising Pune Supergiants 

Sunrisers Hyderabad 

Kolkata Knight Riders 

Kings XI Punjab 

Delhi Daredevils 

Gujarat Lions 

Royal Challengers Bangalore 

