In [5]:
import numpy as np
j = [[0,0,1,1,1,1,1,1],[1,0,1,0,0,0,0,1],[0,0,0,0,1,1,1,1],[0,1,1,0,1,1,1,1],[0,1,0,0,0,0,1,1],[0,1,0,0,1,0,1,0],[0,1,0,0,1,0,0,0],[0,0,0,0,0,1,1,0]]
#from numpy import linalg as LA
y = np.array(j)
print(y)
print()

b = np.array([[1],[1],[1],[1],[1],[1],[1],[1]])
print(b)
print(" b matrix to be multiplied with y matrix")
print()
t_list= [["Mumbai Indians"],["Rising Pune"],["Sunrises Hyderbad"],["kolkata Knight Riders"],["Kings lX Punjab"],["Delhi Capitals"],["Gujarat Lions"],["Royal Challengers Banglore"]]

v = np.matmul(y,b)
print(v)
print("rank of matrix v is = ",np.linalg.matrix_rank(v))
print()
print()

# v = np.matmul(y,b)
print("to find dominant eigen value ","\n"," i use max in-built function")
# t = max(v)
while True:
    v = np.matmul(y,b)
    t = max(v)
    h = []
    for l in v:
        r5 = l/t
        h.append(r5)
    b2 = np.array(h)
    p = np.around(b2,2)
    print(p)
    g =0
    for q in range(8):
        if(p[q][0]==b[q][0]):
            g += 1
    
    if(g==8):
        print("eigen value is ",t)
        print("eigen vector is")
        print(p)
        break
    else:
        b = p
print()
uw = []
for i in range(8):
    for j in range(1):
        uw.append(p[i][j])
print(uw)
print()
name = t_list
count = 1
for i in range(8):
    for j in range(len(uw)):
        k5 = max(uw)
        if(k5==uw[j]):
            print("Rank:-",count,name[j])
            count += 1
            del uw[j]
            del name[j]
            break


[[0 0 1 1 1 1 1 1]
 [1 0 1 0 0 0 0 1]
 [0 0 0 0 1 1 1 1]
 [0 1 1 0 1 1 1 1]
 [0 1 0 0 0 0 1 1]
 [0 1 0 0 1 0 1 0]
 [0 1 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 0]]

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
 b matrix to be multiplied with y matrix

[[6]
 [3]
 [4]
 [6]
 [3]
 [3]
 [2]
 [2]]
rank of matrix v is =  1


to find dominant eigen value  
  i use max in-built function
[[1.  ]
 [0.5 ]
 [0.67]
 [1.  ]
 [0.5 ]
 [0.5 ]
 [0.33]
 [0.33]]
[[1.  ]
 [0.6 ]
 [0.5 ]
 [0.85]
 [0.35]
 [0.4 ]
 [0.3 ]
 [0.25]]
[[1.  ]
 [0.66]
 [0.49]
 [0.91]
 [0.43]
 [0.47]
 [0.36]
 [0.26]]
[[1.  ]
 [0.6 ]
 [0.52]
 [0.91]
 [0.44]
 [0.5 ]
 [0.37]
 [0.28]]
[[1.  ]
 [0.6 ]
 [0.53]
 [0.9 ]
 [0.41]
 [0.47]
 [0.34]
 [0.29]]
[[1.  ]
 [0.62]
 [0.51]
 [0.9 ]
 [0.42]
 [0.46]
 [0.34]
 [0.28]]
[[1.  ]
 [0.62]
 [0.52]
 [0.9 ]
 [0.43]
 [0.47]
 [0.36]
 [0.27]]
[[1.  ]
 [0.61]
 [0.52]
 [0.91]
 [0.42]
 [0.48]
 [0.36]
 [0.28]]
[[1.  ]
 [0.61]
 [0.52]
 [0.9 ]
 [0.42]
 [0.47]
 [0.35]
 [0.28]]
[[1.  ]
 [0.61]
 [0.52]
 [0.9 ]
 [0.42]
 [0.47]
 